# Generated by Django 4.1.4 on 2024-02-15 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paypal", "0004_increase_max_char_length_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expresscheckouttransaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="expresstransaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="payflowtransaction",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
