# Generated by Django 4.1.7 on 2024-01-08 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0026_predefined_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_on_search_menu',
            field=models.BooleanField(default=False),
        ),
    ]
