# Generated by Django 4.1.4 on 2024-04-03 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0006_auto_20181115_1953'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingmethod',
            name='countries',
            field=models.ManyToManyField(blank=True, related_name='Countries', to='address.country'),
        ),
    ]
