# Generated by Django 4.1.7 on 2024-01-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbooklanguages',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='textbookscategories',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
