# Generated by Django 4.1.7 on 2024-01-08 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_textbooklanguages_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textbookclasses',
            name='category',
        ),
        migrations.RemoveField(
            model_name='textbookclasses',
            name='language',
        ),
        migrations.AddField(
            model_name='textbookscategories',
            name='child_classes',
            field=models.ManyToManyField(to='base.textbookclasses'),
        ),
    ]
