# Generated by Django 4.1.4 on 2024-03-03 08:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_shippingmethod_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingmethod",
            name="countries",
        ),
    ]
