# Generated by Django 4.1.7 on 2024-01-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_textbookclasses_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('short_description', models.TextField()),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('link_to_orignal', models.URLField(max_length=1000)),
                ('category', models.ManyToManyField(to='base.educationcategory')),
            ],
        ),
    ]
