# Generated by Django 4.1.4 on 2024-04-16 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_mainmenu_name_en_mainmenu_name_fr'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookscategory',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='bookscategory',
            name='name_fr',
            field=models.CharField(max_length=200, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='culture',
            name='description_en',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='culture',
            name='description_fr',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='culture',
            name='location_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='culture',
            name='location_fr',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='culture',
            name='short_description_en',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='culture',
            name='short_description_fr',
            field=models.TextField(null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='culture',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='culture',
            name='title_fr',
            field=models.CharField(max_length=250, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='culturecategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='culturecategory',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='educationcategory',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='educationcategory',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='footerdetail',
            name='short_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='footerdetail',
            name='short_description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='short_description'),
        ),
        migrations.AddField(
            model_name='footerimportantlinks',
            name='detail_en',
            field=models.TextField(null=True, verbose_name='detail'),
        ),
        migrations.AddField(
            model_name='footerimportantlinks',
            name='detail_fr',
            field=models.TextField(null=True, verbose_name='detail'),
        ),
        migrations.AddField(
            model_name='footerimportantlinks',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='footerimportantlinks',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='textbookclasses',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='textbookclasses',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='textbooklanguages',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='textbooklanguages',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='textbookscategories',
            name='name_en',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='textbookscategories',
            name='name_fr',
            field=models.CharField(max_length=255, null=True, unique=True, verbose_name='name'),
        ),
    ]
