# Generated by Django 4.1.7 on 2024-01-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_educationcategory_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='education_cover/'),
        ),
        migrations.AddField(
            model_name='education',
            name='default',
            field=models.BooleanField(default=False, unique=True),
        ),
        migrations.AlterField(
            model_name='educationcategory',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
