# Generated by Django 4.1.4 on 2024-03-03 09:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0004_shippingmethod_countries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingmethod",
            name="countries",
        ),
    ]
