# Generated by Django 4.1.4 on 2024-04-16 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_bookscategory_name_en_bookscategory_name_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainmenu',
            name='order',
            field=models.SmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
