# Generated by Django 4.1.4 on 2024-03-03 09:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0006_auto_20181115_1953"),
        ("base", "0005_remove_shippingmethod_countries"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethod",
            name="countries",
            field=models.ManyToManyField(
                blank=True, related_name="Countries", to="address.country"
            ),
        ),
    ]
