# Generated by Django 4.1.7 on 2024-01-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_education_cover_image_education_default_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='default',
        ),
        migrations.AddField(
            model_name='educationcategory',
            name='default',
            field=models.BooleanField(default=False, unique=True),
        ),
    ]
