# Generated by Django 4.1.7 on 2024-01-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_education_default_educationcategory_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationcategory',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
