# Generated by Django 4.1.4 on 2024-03-24 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_shippingmethod_countries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='culture',
            options={'ordering': ('-date',)},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-date',)},
        ),
    ]
