# Generated by Django 4.1.4 on 2024-04-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_mainmenu_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainmenu',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='textbooklanguages',
            options={'ordering': ['-name']},
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='name_en',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='name_fr',
            field=models.CharField(max_length=250, null=True, verbose_name='name'),
        ),
    ]
