# Generated by Django 4.1.4 on 2024-03-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_alter_culture_options_alter_education_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='culture',
            name='owner_or_institution_name',
            field=models.CharField(default='admin', max_length=250),
        ),
        migrations.AddField(
            model_name='education',
            name='owner_or_institution_name',
            field=models.CharField(default='admin', max_length=250),
        ),
    ]
