# Generated by Django 4.1.4 on 2024-01-24 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0028_category_main_book_category"),
        ("base", "0008_culturecategory_alter_education_cover_image_culture"),
    ]

    operations = [
        migrations.CreateModel(
            name="MainMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("icons_link", models.TextField(blank=True, max_length=200, null=True)),
                (
                    "redirect_to_link",
                    models.URLField(
                        help_text='After, clicking on the main menu the user will redirect to this LINK. Please keep it blank if you want to attached any category to the main menu and select the category in below field(name "Category Attached")',
                        null=True,
                    ),
                ),
                (
                    "category_attached",
                    models.ForeignKey(
                        blank=True,
                        help_text="Please choose the Category if you don't attach any redirect link, if you will attach the both, priority will be for Category field.",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="catalogue.category",
                    ),
                ),
            ],
        ),
    ]
