# Generated by Django 4.1.4 on 2024-02-06 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_alter_mainmenu_icons_link_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mainmenu",
            name="redirect_to_link",
            field=models.CharField(
                blank=True,
                help_text='Please write the url like /abc/abc/1, do not include any domain or IP address before the URL. This url will redirect users to this LINK. Please keep it blank if you want to attached any category to the main menu and select the category in below field(name "Category Attached")',
                max_length=1000,
                null=True,
            ),
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                (
                    "code",
                    models.CharField(
                        help_text="Please don't give any space in this field",
                        max_length=250,
                    ),
                ),
                ("charge_excl_tax", models.IntegerField()),
                ("charge_incl_tax", models.IntegerField()),
                (
                    "child_of",
                    models.ForeignKey(
                        help_text="If you choose this, then this will become a child (not a parent)",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.shippingmethod",
                    ),
                ),
            ],
        ),
    ]
