# Generated by Django 4.1.4 on 2024-03-25 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=200, null=True)),
                ('short_description', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
