# Generated by Django 4.1.4 on 2024-03-25 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_footerdetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FooterDetails',
            new_name='FooterDetail',
        ),
    ]
