# Generated by Django 4.1.4 on 2024-02-14 09:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone_number",
        ),
    ]
