# Generated by Django 4.1.4 on 2024-03-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_footerdetails_footerdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footerdetail',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
