# Generated by Django 4.1.4 on 2024-02-14 09:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_remove_user_phone_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
