# Generated by Django 4.1.4 on 2024-04-02 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_siteinfo_culture_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='culture',
            name='date',
            field=models.DateField(),
        ),
    ]
