# Generated by Django 4.1.4 on 2024-04-02 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_culture_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FooterImportantLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('detail', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='SiteInfo',
        ),
    ]
