# Generated by Django 4.1.4 on 2024-02-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0018_alter_user_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                max_length=254,
                null=True,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
