# Generated by Django 4.1.4 on 2024-04-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_footerimportantlinks_delete_siteinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footerimportantlinks',
            name='link',
        ),
    ]
