# Generated by Django 4.1.4 on 2024-02-16 12:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0020_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
