# Generated by Django 4.1.4 on 2024-02-16 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0021_remove_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
