# Generated by Django 4.1.4 on 2024-02-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0006_auto_20181115_1953"),
        ("base", "0022_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="shippingmethod",
            name="country",
            field=models.ManyToManyField(to="address.country", verbose_name="Country"),
        ),
    ]
