# Generated by Django 4.1.4 on 2024-02-17 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0006_auto_20181115_1953"),
        ("base", "0023_shippingmethod_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shippingmethod",
            name="country",
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="countries",
            field=models.ManyToManyField(
                blank=True, to="address.country", verbose_name="Countries"
            ),
        ),
    ]
