# Generated by Django 4.1.4 on 2024-02-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("address", "0006_auto_20181115_1953"),
        ("base", "0024_remove_shippingmethod_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingmethod",
            name="countries",
            field=models.ManyToManyField(
                blank=True, related_name="Countries", to="address.country"
            ),
        ),
    ]
