# Generated by Django 4.1.4 on 2024-02-19 14:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0025_alter_shippingmethod_countries"),
    ]

    operations = [
        migrations.CreateModel(
            name="RateofEuro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("base", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                ("euro_rate", models.FloatField()),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
