# Generated by Django 4.1.4 on 2024-02-19 15:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0026_rateofeuro"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rateofeuro",
            old_name="euro_rate",
            new_name="xaf_to_euro",
        ),
    ]
